version: "3.3"

services:
  db:
    image: postgres:13.8
    environment:
      - POSTGRES_DB=sb3_jooq_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql